# Generated by Django 4.2.1 on 2023-06-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='from_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
