# Generated by Django 4.2.1 on 2023-06-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_date',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact_date',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contact_date',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact_date',
            old_name='subject',
            new_name='Subject',
        ),
    ]
