# Generated by Django 4.2.1 on 2023-06-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_email_contact_date_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='from_date',
            old_name='email',
            new_name='Email',
        ),
    ]
