# Generated by Django 4.2.1 on 2023-06-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='Email',
            new_name='Email1',
        ),
    ]
