# Generated by Django 4.2.1 on 2023-06-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_email_leave_email1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='Email1',
            new_name='Email',
        ),
    ]
